package yarn

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/jumoel/locksmith/ecosystem"
)

// mockRegistry implements ecosystem.Registry for testing.
type mockRegistry struct {
	packages map[string]*mockPackage
}

type mockPackage struct {
	versions map[string]*ecosystem.VersionMetadata
	times    map[string]time.Time
}

func newMockRegistry() *mockRegistry {
	return &mockRegistry{packages: make(map[string]*mockPackage)}
}

func (m *mockRegistry) addVersion(name, version string, published time.Time, deps map[string]string) {
	m.addVersionFull(name, version, published, deps, nil)
}

func (m *mockRegistry) addVersionFull(name, version string, published time.Time, deps, optDeps map[string]string) {
	pkg, ok := m.packages[name]
	if !ok {
		pkg = &mockPackage{
			versions: make(map[string]*ecosystem.VersionMetadata),
			times:    make(map[string]time.Time),
		}
		m.packages[name] = pkg
	}
	pkg.versions[version] = &ecosystem.VersionMetadata{
		Name:         name,
		Version:      version,
		Integrity:    fmt.Sprintf("sha512-fake-%s-%s", name, version),
		TarballURL:   fmt.Sprintf("https://registry.yarnpkg.com/%s/-/%s-%s.tgz", name, name, version),
		Dependencies: deps,
		OptionalDeps: optDeps,
	}
	pkg.times[version] = published
}

func (m *mockRegistry) FetchVersions(ctx context.Context, name string, cutoff *time.Time) ([]ecosystem.VersionInfo, error) {
	pkg, ok := m.packages[name]
	if !ok {
		return nil, fmt.Errorf("package %s not found", name)
	}
	var versions []ecosystem.VersionInfo
	for v, t := range pkg.times {
		if cutoff != nil && t.After(*cutoff) {
			continue
		}
		versions = append(versions, ecosystem.VersionInfo{
			Version:     v,
			PublishedAt: t,
		})
	}
	return versions, nil
}

func (m *mockRegistry) FetchMetadata(ctx context.Context, name, version string) (*ecosystem.VersionMetadata, error) {
	pkg, ok := m.packages[name]
	if !ok {
		return nil, fmt.Errorf("package %s not found", name)
	}
	meta, ok := pkg.versions[version]
	if !ok {
		return nil, fmt.Errorf("version %s of %s not found", version, name)
	}
	return meta, nil
}

func (m *mockRegistry) FetchDistTags(ctx context.Context, name string) (map[string]string, error) {
	pkg, ok := m.packages[name]
	if !ok {
		return nil, fmt.Errorf("package %s not found", name)
	}
	var latest string
	for v := range pkg.versions {
		if latest == "" || v > latest {
			latest = v
		}
	}
	return map[string]string{"latest": latest}, nil
}

// baseTime is a fixed reference point for test timestamps.
var baseTime = time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)

func TestYarnClassic_SimpleProject(t *testing.T) {
	reg := newMockRegistry()
	reg.addVersion("is-number", "6.0.0", baseTime, nil)
	reg.addVersion("is-odd", "3.0.1", baseTime, map[string]string{"is-number": "^6.0.0"})

	project := &ecosystem.ProjectSpec{
		Name:    "test-project",
		Version: "1.0.0",
		Dependencies: []ecosystem.DeclaredDep{
			{Name: "is-odd", Constraint: "^3.0.0", Type: ecosystem.DepRegular},
		},
	}

	resolver := NewResolver()
	result, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	formatter := NewYarnClassicFormatter()
	output, err := formatter.FormatFromResult(result, project)
	if err != nil {
		t.Fatalf("format failed: %v", err)
	}

	lockfile := string(output)
	t.Logf("Generated lockfile:\n%s", lockfile)

	// Verify header.
	if !strings.HasPrefix(lockfile, "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n") {
		t.Error("missing or incorrect header")
	}

	// Verify is-number entry.
	if !strings.Contains(lockfile, "is-number@^6.0.0:") {
		t.Error("missing is-number@^6.0.0 constraint key")
	}
	if !strings.Contains(lockfile, `version "6.0.0"`) {
		t.Error("missing is-number version")
	}
	if !strings.Contains(lockfile, `integrity sha512-fake-is-number-6.0.0`) {
		t.Error("missing is-number integrity")
	}

	// Verify is-odd entry.
	if !strings.Contains(lockfile, "is-odd@^3.0.0:") {
		t.Error("missing is-odd@^3.0.0 constraint key")
	}
	if !strings.Contains(lockfile, `version "3.0.1"`) {
		t.Error("missing is-odd version")
	}

	// Verify is-odd has dependencies section with constraint (not resolved version).
	if !strings.Contains(lockfile, "  dependencies:\n") {
		t.Error("missing dependencies section for is-odd")
	}
	if !strings.Contains(lockfile, `    is-number "^6.0.0"`) {
		t.Error("missing is-number dependency constraint in is-odd entry")
	}
}

func TestYarnClassic_MultipleConstraintsSameVersion(t *testing.T) {
	reg := newMockRegistry()
	// Both ^1.0.0 and ^1.1.0 should resolve to 1.2.0
	reg.addVersion("shared-dep", "1.2.0", baseTime, nil)
	reg.addVersion("A", "1.0.0", baseTime, map[string]string{"shared-dep": "^1.0.0"})
	reg.addVersion("B", "1.0.0", baseTime, map[string]string{"shared-dep": "^1.1.0"})

	project := &ecosystem.ProjectSpec{
		Name:    "test-project",
		Version: "1.0.0",
		Dependencies: []ecosystem.DeclaredDep{
			{Name: "A", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
			{Name: "B", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
		},
	}

	resolver := NewResolver()
	result, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	formatter := NewYarnClassicFormatter()
	output, err := formatter.FormatFromResult(result, project)
	if err != nil {
		t.Fatalf("format failed: %v", err)
	}

	lockfile := string(output)
	t.Logf("Generated lockfile:\n%s", lockfile)

	// Both constraints should appear on the same entry line.
	if !strings.Contains(lockfile, "shared-dep@^1.0.0, shared-dep@^1.1.0:") {
		t.Error("expected merged constraint keys for shared-dep")
		t.Logf("Looking for: shared-dep@^1.0.0, shared-dep@^1.1.0:")
	}

	// Should only have ONE version "1.2.0" line for shared-dep.
	count := strings.Count(lockfile, `version "1.2.0"`)
	if count != 1 {
		t.Errorf("expected exactly 1 version line for shared-dep 1.2.0, got %d", count)
	}
}

func TestYarnClassic_DeterministicOutput(t *testing.T) {
	reg := newMockRegistry()
	reg.addVersion("Z-pkg", "1.0.0", baseTime, nil)
	reg.addVersion("A-pkg", "2.0.0", baseTime, nil)
	reg.addVersion("M-pkg", "3.0.0", baseTime, map[string]string{
		"Z-pkg": "^1.0.0",
		"A-pkg": "^2.0.0",
	})

	project := &ecosystem.ProjectSpec{
		Name:    "test-project",
		Version: "1.0.0",
		Dependencies: []ecosystem.DeclaredDep{
			{Name: "M-pkg", Constraint: "^3.0.0", Type: ecosystem.DepRegular},
			{Name: "Z-pkg", Constraint: "^1.0.0", Type: ecosystem.DepDev},
		},
	}

	resolver := NewResolver()
	formatter := NewYarnClassicFormatter()

	result1, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("first resolve failed: %v", err)
	}
	output1, err := formatter.FormatFromResult(result1, project)
	if err != nil {
		t.Fatalf("first format failed: %v", err)
	}

	result2, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("second resolve failed: %v", err)
	}
	output2, err := formatter.FormatFromResult(result2, project)
	if err != nil {
		t.Fatalf("second format failed: %v", err)
	}

	if !bytes.Equal(output1, output2) {
		t.Error("output is not deterministic across runs")
		t.Logf("First:\n%s", string(output1))
		t.Logf("Second:\n%s", string(output2))
	}
}

func TestYarnClassic_SortedEntries(t *testing.T) {
	reg := newMockRegistry()
	reg.addVersion("z-last", "1.0.0", baseTime, nil)
	reg.addVersion("a-first", "1.0.0", baseTime, nil)
	reg.addVersion("m-middle", "1.0.0", baseTime, nil)

	project := &ecosystem.ProjectSpec{
		Name:    "test-project",
		Version: "1.0.0",
		Dependencies: []ecosystem.DeclaredDep{
			{Name: "z-last", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
			{Name: "a-first", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
			{Name: "m-middle", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
		},
	}

	resolver := NewResolver()
	result, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	formatter := NewYarnClassicFormatter()
	output, err := formatter.FormatFromResult(result, project)
	if err != nil {
		t.Fatalf("format failed: %v", err)
	}

	lockfile := string(output)

	// Verify alphabetical order.
	aIdx := strings.Index(lockfile, "a-first@")
	mIdx := strings.Index(lockfile, "m-middle@")
	zIdx := strings.Index(lockfile, "z-last@")

	if aIdx == -1 || mIdx == -1 || zIdx == -1 {
		t.Fatal("missing expected entries")
	}
	if !(aIdx < mIdx && mIdx < zIdx) {
		t.Error("entries are not sorted alphabetically")
	}
}

func TestYarnClassic_FormatInterfaceReturnsError(t *testing.T) {
	formatter := NewYarnClassicFormatter()
	_, err := formatter.Format(nil, nil)
	if err == nil {
		t.Fatal("expected error from Format(), got nil")
	}
	if !strings.Contains(err.Error(), "FormatFromResult") {
		t.Errorf("expected error mentioning FormatFromResult, got: %v", err)
	}
}

func TestYarnClassic_NoDepsNoDependenciesSection(t *testing.T) {
	reg := newMockRegistry()
	reg.addVersion("leaf-pkg", "1.0.0", baseTime, nil)

	project := &ecosystem.ProjectSpec{
		Name:    "test-project",
		Version: "1.0.0",
		Dependencies: []ecosystem.DeclaredDep{
			{Name: "leaf-pkg", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
		},
	}

	resolver := NewResolver()
	result, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	formatter := NewYarnClassicFormatter()
	output, err := formatter.FormatFromResult(result, project)
	if err != nil {
		t.Fatalf("format failed: %v", err)
	}

	lockfile := string(output)

	// A leaf package with no dependencies should NOT have a dependencies: section.
	if strings.Contains(lockfile, "dependencies:") {
		t.Error("leaf package should not have dependencies section")
	}
}

func TestYarnClassic_TransitiveDeps(t *testing.T) {
	reg := newMockRegistry()
	reg.addVersion("A", "1.0.0", baseTime, map[string]string{"B": "^2.0.0"})
	reg.addVersion("B", "2.1.0", baseTime, map[string]string{"C": "^1.0.0"})
	reg.addVersion("C", "1.3.0", baseTime, nil)

	project := &ecosystem.ProjectSpec{
		Name:    "test-project",
		Version: "1.0.0",
		Dependencies: []ecosystem.DeclaredDep{
			{Name: "A", Constraint: "^1.0.0", Type: ecosystem.DepRegular},
		},
	}

	resolver := NewResolver()
	result, err := resolver.ResolveForLockfile(context.Background(), project, reg, ecosystem.ResolveOptions{})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	formatter := NewYarnClassicFormatter()
	output, err := formatter.FormatFromResult(result, project)
	if err != nil {
		t.Fatalf("format failed: %v", err)
	}

	lockfile := string(output)
	t.Logf("Generated lockfile:\n%s", lockfile)

	// All three packages should appear.
	if !strings.Contains(lockfile, "A@^1.0.0:") {
		t.Error("missing A entry")
	}
	if !strings.Contains(lockfile, "B@^2.0.0:") {
		t.Error("missing B entry")
	}
	if !strings.Contains(lockfile, "C@^1.0.0:") {
		t.Error("missing C entry")
	}

	// Verify resolved versions.
	if !strings.Contains(lockfile, `version "1.0.0"`) {
		t.Error("missing A version 1.0.0")
	}
	if !strings.Contains(lockfile, `version "2.1.0"`) {
		t.Error("missing B version 2.1.0")
	}
	if !strings.Contains(lockfile, `version "1.3.0"`) {
		t.Error("missing C version 1.3.0")
	}
}
